### ISSUE TITLE
内网ECS，运行 tnvm upgrade 终端卡死

### ISSUE THREAD

**Issue by nick-ma** [ali-sdk/tnvm#11]
这个场景主要是忘了配置https的代理，即忘了 export https_proxy=xxx.xxx.xxx.xxx:xxxxx 。
问题应该发生在wget这个命令。

```
wget -qO- https://raw.githubusercontent.com/ali-sdk/tnvm/master/install.sh
```

现在只能登录另外一个终端，把这个进程杀掉才行。在原来的终端，按 ctrl-c 也退不出来。
希望能优化一下。发现网络连不通，报个错然后退出就行了。

**Comment by yjhjstz** [comment]
嗯嗯，赞

**Comment by yjhjstz** [comment]
@nick-ma 能否帮忙提交一个PR呢？我这边没有环境重现不了。

**Comment by JacksonTian** [comment]
你wget -q0- faceboock 试试就好了

**Comment by JacksonTian** [comment]
close via #13
