### ISSUE TITLE
内网使用代理可以如何使用这个脚本？

### ISSUE THREAD

**Issue by p2227** [ali-sdk/tnvm#18]
export METHOD=script
curl -k -o- https://raw.githubusercontent.com/creationix/nvm/v0.32.0/install.sh | bash
wget --no-check-certificate -O- https://raw.githubusercontent.com/aliyun-node/tnvm/master/install.sh | bash

各种试过都无法安装和使用，如何增加一个不校验ssl证书的参数？

**Comment by yjhjstz** [comment]
报什么错呢？

**Comment by p2227** [comment]
卡在下载tnvm.sh不动
估计在下载nodejs的时候也会，因为用nvm的情况是差不多的

**Comment by yjhjstz** [comment]
有配置 curl , wget 的HTTPS代理吗？

**Comment by JacksonTian** [comment]
需要设置代理吧。

**Comment by p2227** [comment]
嗯，代理是设置了，否则也不会下载到`install.sh` 然后里面解释出要下载`tnvm.sh`
我大概知道原因，我公司的代理会把https的证书替换成自己的，也就是传说中的中间人。唯有客户端不去校验这个证书，才能建立起https连接。
所以我用 curl -k 参数可以下载`install.sh` 
但里面再下载`tnvm.sh`的时候，没有继续传递这个参数，所以下载不成功的

比如 `curl --verbose https://nodejs.org/dist/`
会报`error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed`

**Comment by p2227** [comment]
http://unix.stackexchange.com/questions/60750/does-curl-have-a-no-check-certificate-option-like-wget/109649#109649
我配置了这个解决了，似乎淘宝的源可以用http连接
