### ISSUE TITLE
tnvm存在browserify使用上的报错BUG

### ISSUE THREAD

**Issue by zy445566** [ali-sdk/tnvm#31]
我使用nvm跑下面例子的时候发现以下情况
https://github.com/socketio/socket.io-p2p/tree/master/examples/chat
![image](https://user-images.githubusercontent.com/14976489/31495010-628c0cf6-af1b-11e7-93f4-9d753afff58d.png)
而我换回nvm则回复正常
![image](https://user-images.githubusercontent.com/14976489/31495121-eb5bbdba-af1b-11e7-9022-02b3d375ca89.png)

两个环境的browserify，我都重新安装过了

**Comment by joyeecheung** [comment]
第一张图看上去不是用 npm 安装的，用npm安装试试？

**Comment by joyeecheung** [comment]
试了一下，cnpm 安装的 browserify 会有这个问题，npm 不会，大概和 cnpm 对路径的处理有关。

**Comment by joyeecheung** [comment]
nvm + cnpm 安装的 browserify 也有这个问题，tnvm 和 nvm 的路径处理是类似的，从你的截图来看，第二次成功是因为你用 npm 安装了 browserify。请到 cnpm 提这个 issue。

**Comment by zy445566** [comment]
😳  就算是cnpm的问题，你这边也关的太急了吧。
至少等我一天吧，没确认再关吧。。。
<br />
<br />
<br />
<br />
<br />
<br />
<br />
-----------------------------
不过也不要紧 哈哈(∩_∩)

**Comment by joyeecheung** [comment]
抱歉，我习惯定位到不是bug之后就关闭，因为有问题可以再开。
