### ISSUE TITLE
sh 环境下运行报错

### ISSUE THREAD

**Issue by axetroy** [ali-sdk/tnvm#35]
install.sh 和tnvm.sh 很久没更新了吧

install之后

```bash
source ~/.bashrc
```

这样报错

然后以 sh 运行 tnvm 也报错...

官方给的 docker 镜像也是 ``centerOS``, 没有``alpine``呀

**Comment by hyj1991** [comment]
@axetroy 有 alphie，https://help.aliyun.com/document_detail/65376.html
