### ISSUE TITLE
安装完后环境变量PATH配置不正确

### ISSUE THREAD

**Issue by yunnysunny** [ali-sdk/tnvm#36]
sunny@sunny-OptiPlex-7040:~$ npm
fs.js:1003
  binding.lstat(pathModule._makeLong(path), statValues);
          ^

Error: ENOENT: no such file or directory, lstat '/home/sunny//versions'
    at Error (native)
    at Object.fs.lstatSync (fs.js:1003:11)
    at Object.realpathSync (fs.js:1684:21)
    at toRealPath (module.js:140:13)
    at Function.Module._findPath (module.js:188:22)
    at Function.Module._resolveFilename (module.js:474:25)
    at Function.Module._load (module.js:424:25)
    at Module.runMain (module.js:611:10)
    at run (bootstrap_node.js:387:7)
    at startup (bootstrap_node.js:153:9)

执行 which node，打印 /versions/alinode/v2.5.0/bin，但是我本机没有这个目录
查看 $PATH 变量，发现里面含有目录 `//versions/alinode/v2.5.0/bin`，应该就是这个原因导致的，tnvm的安装脚本，在环境变量中写入了错误的环境变量。

**Comment by hyj1991** [comment]
@zhangzifa

**Comment by zhangzifa** [comment]
@yunnysunny 抱歉回复晚了，你的服务器上 HOME 目录是什么

**Comment by yunnysunny** [comment]
/home/sunny

**Comment by zhangzifa** [comment]
～/.bashrc 里面 有两行，带了TNVM字段的，你的是? 我的是这样的
```shell
export TNVM_DIR="/home/zhangzifa/.tnvm"
[ -s "$TNVM_DIR/tnvm.sh" ] && . "$TNVM_DIR/tnvm.sh"  # This loads nvm
```

**Comment by yunnysunny** [comment]
我检查了一下`~/.bashrc`，
```shell
export TNVM_DIR="/home/sunny/.tnvm"
[ -s "$TNVM_DIR/tnvm.sh" ] && . "$TNVM_DIR/tnvm.sh"  # This loads nvm
```
然后重新`source ~/.bashrc`
然后运行`echo $PATH`,还是发现`/versions/alinode/v2.5.0/bin`

**Comment by zhangzifa** [comment]
@yunnysunny  加一下钉钉？这里效率太低啦 我的 穆客

**Comment by yunnysunny** [comment]
已经添加

**Comment by yunnysunny** [comment]
赋值语句 export TNVM_DIR="/home/sunny/.tnvm" 中有特殊字符导致的，字符串末尾有一个回车符，平常没有注意到，修正后，环境变量正常了。
