### ISSUE TITLE
在 Mac 上 怎么安装 alinode 

### ISSUE THREAD

**Issue by HenryZhu-1988** [ali-sdk/tnvm#38]

**Comment by hyj1991** [comment]
参照 https://help.aliyun.com/document_detail/60902.html

**Comment by HenryZhu-1988** [comment]
就是 按照 这个文档来的的 source ~/.bashrc 说是找不到 这个 文件

**Comment by zhangzifa** [comment]
一般用户是 .bashrc，你如果用了另外的shell的就用自己的那个

**Comment by hyj1991** [comment]
如果没有的话创建一个 ~/.bashrc 文件，添加一个 ~/.bash_profile 文件：

```bash
source ~/.bashrc
```

**Comment by hyj1991** [comment]
mac 下没有 wget 就用 curl 安装：

```bash
curl https://raw.githubusercontent.com/aliyun-node/tnvm/master/install.sh | bash
```

**Comment by hyj1991** [comment]
Hi，mac 下安装可以了不，ok 的话可以关掉这个 issue；还有问题的话，可以继续在这里问
