### ISSUE TITLE
这个安装脚本，在 Ubuntu docker 上就是个坑...

### ISSUE THREAD

**Issue by wsdo** [ali-sdk/tnvm#46]

**Comment by peze** [comment]
怎么说？

**Comment by wsdo** [comment]
> 怎么说？

有案例么，
# install alinode
RUN wget -O- https://raw.githubusercontent.com/aliyun-node/tnvm/master/install.sh | bash

RUN echo 'export TNVM_DIR="/root/.tnvm"' >> ~/.bashrc

RUN source ~/.bashrc \
    && tnvm install alinode-v4.3.0 \
    && tnvm use alinode-v4.3.0 \
    && npm install @alicloud/agenthub -g \
    && npm config set registry https://registry.npm.taobao.org \
    && npm install pm2 -g --productio

怎么弄 最后 tnvm 总是找不到

**Comment by peze** [comment]
可能是那个github的地址不是很稳定 可以把那个install.sh直接复制下来 然后COPY进镜像执行

**Comment by wsdo** [comment]
> 可能是那个github的地址不是很稳定 可以把那个install.sh直接复制下来 然后COPY进镜像执行

不是的，在docker官方跑的，网络肯定稳定，就是感觉不应该 写在~/.bashrc 为啥不用 ln 这种方式，就像 node 官方 安装node的那种方式呢

**Comment by peze** [comment]
nvm本身也是用这种bashrc的形式啊

**Comment by wsdo** [comment]
> nvm本身也是用这种bashrc的形式啊

https://github.com/rdmix/docker-alinode 最后解决了

**Comment by kimown** [comment]
找不到tnvm，可以执行这个命令`source ~/.tnvm/tnvm.sh`

**Comment by xmsz** [comment]
太坑了
